[package]
name = "dcsctp"
description = "An SCTP implementation for WebRTC Data Channels"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/webrtc/dcsctp"
keywords = ["webrtc", "sctp"]
categories = ["network-programming"]

[dependencies]
anyhow = "1.0.98"
crc-any = "2.5.0"
log = "0.4.27"
rand = "0.9.1"
thiserror = "2.0.12"

[dev-dependencies]
itertools = "0.14.0"

[features]
fuzz-internals = []

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(fuzzing)', 'cfg(feature, values("fuzz-internals"))'] }
